name: docker-build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    uses: liveviewtech/actions/.github/workflows/buildx.yml@v1.0
    with:
      image-name: gregs_test
    secrets: inherit
